name = "tawasol-alatta"
main = "src/worker.js"
compatibility_date = "2026-10-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "SIGNALING"
class_name = "SignalingRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]
